### ISSUE TITLE
Inconsistent display of pathway table of content items

### ISSUE THREAD

**Issue by pherterich** [the-turing-way/pathways#35]
Some items in the pathway display in line where other parts are indented bullet points that make it more clear that these are separate sections:

![Image](https://github.com/user-attachments/assets/a628f75e-8e00-4fa0-99ab-1922d12edf1b)

If there is some logic behind this from this example the ones that are displaying in line seem to be all having "overview" in their file path.

**Comment by malvikasharan** [comment]
There is some bug that is causing the formatting error.

I can check and see what might be causing chapters to not appear in list format.

**Comment by JimMadge** [comment]
There is an extra level of indentation which seems to cause it to render like this

```markdown
These are the pages curated for PROJECT LEADERS
- [](../reproducible-research/reproducible-research.md)
        - [](../reproducible-research/overview/overview-definitions.md)
        - [](../reproducible-research/overview/overview-barriers.md)
    - [](../reproducible-research/open.md)
        - [](../reproducible-research/open/open-data.md)
        - [](../reproducible-research/open/open-source.md)
- [](../project-design/project-design.md)
        - [](../project-design/pd-overview/pd-overview-planning.md)
        - [](../project-design/pd-overview/pd-overview-repro.md)
        - [](../project-design/pd-overview/pd-overview-methods.md)
        - [](../project-design/pd-overview/pd-overview-version.md)
    - [](../project-design/project-repo.md)
    - [](../collaboration/leadership.md)
```

The indentation seems to be based on the ToC, see how "Definitions" is in the "Overview" chapter of the Guide for Reproducible Research. But the "Overview" chapter isn't in the list.

**Comment by JimMadge** [comment]
We could,

- Handle 'skipped' ToC levels
  - automatically include skipped parents?
  - reduce indent?
- Catch these cases and return and error

**Comment by LelleDi** [comment]
I'm encountering the same issue with the Operational Community Management pathway https://github.com/the-turing-way/the-turing-way/pull/4194

**Comment by JimMadge** [comment]
A workaround would be, to make sure the all "parents" are added to a pathway in `profiles.yml`.

For example

```yaml
- name: Project Leaders
  files:
    - reproducible-research/reproducible-research.md
    - reproducible-research/overview/overview-definitions.md
```

becomes

```yaml
- name: Project Leaders
  files:
    - reproducible-research/reproducible-research.md
    - reproducible-research/overview.md
    - reproducible-research/overview/overview-definitions.md
```
